### ISSUE TITLE
分割符可以是两个以上字符吗？

### ISSUE THREAD

**Issue by norlover** [origingod/SocialEngineerDBuilder#1]
[root@localhost SocialEngineerDBuilder-master]# head csdn.tmpl 
SPACE#SPACE username|password|email
[root@localhost SocialEngineerDBuilder-master]# head csdn.sql  
zdg # 12344321 # zdg@csdn.net
LaoZheng # 670203313747 # chengming_zheng@163.com
fstao # 730413 # fstao@tom.com
huwolf # 2535263 # hujiye@263.net
cadcjl # KIC43dk6! # ccedcjl@21cn.com
netsky # s12345 # songmail@21cn.com
Michael # apple # appollp@netease.com
siclj # lj7202 # junlu@peoplemail.com.cn

[root@localhost SocialEngineerDBuilder-master]# python SG.py csdn.sql csdn.tmpl                   
Traceback (most recent call last):
  File "SG.py", line 174, in <module>
    save_all_to_db()
  File "SG.py", line 101, in save_all_to_db
    user_class = gen_parse_class(sys.argv[2])
  File "SG.py", line 24, in gen_parse_class
    if not check_col_name(columns): raise Exception('Invalid column name!')
NameError: global name 'check_col_name' is not defined

**Comment by origingod** [comment]
支持两个以上字符，但是不同时支持'SPACE'特殊字符，这个例子里面只需要把'#'当成分隔符，因为会自动把空格过滤掉的。

**Comment by norlover** [comment]
[root@localhost SocialEngineerDBuilder-master]# head  csdn.sql
zdg # 12344321 # zdg@csdn.net
LaoZheng # 670203313747 # chengming_zheng@163.com
fstao # 730413 # fstao@tom.com
huwolf # 2535263 # hujiye@263.net
cadcjl # KIC43dk6! # ccedcjl@21cn.com
netsky # s12345 # songmail@21cn.com
Michael # apple # appollp@netease.com
siclj # lj7202 # junlu@peoplemail.com.cn
jinbuhuan # 12345 # jinbuhuan@163.net
Eie # hebeibdh # fwg@jxfw.com
[root@localhost SocialEngineerDBuilder-master]# head  csdn.tmpl
# username|password|email
[root@localhost SocialEngineerDBuilder-master]#
[root@localhost SocialEngineerDBuilder-master]#
[root@localhost SocialEngineerDBuilder-master]#  python SG.py csdn.sql csdn.tmpl
Traceback (most recent call last):
  File "SG.py", line 174, in <module>
    save_all_to_db()
  File "SG.py", line 101, in save_all_to_db
    user_class = gen_parse_class(sys.argv[2])
  File "SG.py", line 24, in gen_parse_class
    if not check_col_name(columns): raise Exception('Invalid column name!')
NameError: global name 'check_col_name' is not defined

还是这样的错误，奇怪

**Comment by origingod** [comment]
咳咳，不好意思，是个bug。这个版本应该ok
